# 电商智能客服RAG系统配置文件

# 缓存配置
cache:
  # Redis配置
  redis:
    host: localhost
    port: 6379
    db: 0
    password: null
    socket_timeout: 5
    socket_connect_timeout: 5
    socket_keepalive: true
    socket_keepalive_options: {}
    
  # L1内存缓存配置
  l1_cache:
    size: 1000
    ttl: 3600  # 1小时
    
  # L2 Redis缓存配置
  l2_cache:
    ttl: 7200  # 2小时
    
  # L3数据库缓存配置
  l3_cache:
    ttl: 86400  # 24小时

# 数据库配置
database:
  # PostgreSQL配置
  postgresql:
    host: localhost
    port: 5432
    database: ecommerce_rag
    username: postgres
    password: password
    pool_size: 5
    max_overflow: 10
    
  # SQLite配置（开发环境）
  sqlite:
    path: ./data/ecommerce.db

# 向量数据库配置
vector_store:
  # Elasticsearch配置
  elasticsearch:
    host: localhost
    port: 9200
    index_name: ecommerce_vectors
    username: null
    password: null
    
  # Chroma配置
  chroma:
    host: localhost
    port: 8000
    collection_name: ecommerce_collection
    
  # 配置选择哪个向量数据库
  provider: "mock"  # 可选: elasticsearch, chroma, mock

# 消息队列配置
message_queue:
  # Redis队列配置
  redis:
    host: localhost
    port: 6379
    db: 1
    queue_name: "data_sync_queue"
    
  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue_name: "data_sync"
    
  # 配置选择哪个消息队列
  provider: "redis"  # 可选: redis, rabbitmq, mock

# 系统配置
system:
  # 搜索配置
  search:
    max_results: 10
    similarity_threshold: 0.5
    
  # 数据处理配置
  data_processing:
    chunk_size: 500
    chunk_overlap: 50
    max_question_variants: 10
    
  # 缓存配置
  cache_priority_threshold:
    high: 0.8
    medium: 0.5
    low: 0.2
    
  # 用户分类配置
  user_classification:
    vip_threshold: 3
    frequent_user_threshold: 5
    
  # 响应配置
  response:
    max_context_length: 2000
    answer_max_length: 1000
    include_sources: true

# 日志配置
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/ecommerce_rag.log"
  max_file_size: 10MB
  backup_count: 5

# 监控配置
monitoring:
  # 性能指标
  metrics:
    enabled: true
    collection_interval: 60  # 秒
    
  # 告警配置
  alerts:
    enabled: true
    email_recipients: ["admin@example.com"]
    
  # 响应时间阈值
  response_time_thresholds:
    warning: 1.0  # 秒
    critical: 3.0  # 秒
    
  # 缓存命中率阈值
  cache_hit_rate_thresholds:
    warning: 0.7
    critical: 0.5

# 安全配置
security:
  # API密钥
  api_keys:
    openai: "your-openai-api-key"
    pinecone: "your-pinecone-api-key"
    
  # 访问控制
  access_control:
    enabled: true
    rate_limit: 100  # 每分钟请求数
    
  # 数据加密
  encryption:
    enabled: false
    key: "your-encryption-key"

# 开发配置
development:
  # 调试模式
  debug: true
  
  # 测试数据
  use_sample_data: true
  
  # 模拟服务
  mock_services:
    vector_store: true
    llm: true
    cache: false

# 生产配置
production:
  # 性能配置
  performance:
    worker_count: 4
    max_concurrent_requests: 100
    
  # 高可用配置
  high_availability:
    enabled: true
    health_check_interval: 30
    
  # 备份配置
  backup:
    enabled: true
    interval: 3600  # 1小时
    retention_days: 30